on:
  pull_request:
    types: [closed]
jobs:
  git-sync:
    if: ${{ startsWith(github.event.pull_request.title, 'all') }}
    runs-on: ubuntu-latest
    steps:
      - name: git-sync-staging
        uses: wei/git-sync@v3
        with:
          source_repo: "https://johnduenas1000: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@github.com/jdtest-github-actions/develop.git" #URL primer repositorio.
          source_branch: "main"
          destination_repo: https://johnduenas1000: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@github.com/jdtest-github-actions/staging.git #Repositorio destino.
          destination_branch: "main"
      - name: git-sync-production
        uses: wei/git-sync@v3
        with:
          source_repo: "https://johnduenas1000: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@github.com/jdtest-github-actions/develop.git" #URL primer repositorio.
          source_branch: "main"
          destination_repo: https://johnduenas1000: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@github.com/jdtest-github-actions/production.git #Repositorio destino.
          destination_branch: "main"
    if: ${{ startsWith(github.event.pull_request.title, 'staging') }}
    runs-on: ubuntu-latest
    steps:
      - name: git-sync-staging
        uses: wei/git-sync@v3
        with:
          source_repo: "https://johnduenas1000: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@github.com/jdtest-github-actions/develop.git" #URL primer repositorio.
          source_branch: "main"
          destination_repo: https://johnduenas1000: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@github.com/jdtest-github-actions/staging.git #Repositorio destino.
          destination_branch: "main"
    if: ${{ startsWith(github.event.pull_request.title, 'production') }}
    runs-on: ubuntu-latest
    steps:
      - name: git-sync-production
        uses: wei/git-sync@v3
        with:
          source_repo: "https://johnduenas1000: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@github.com/jdtest-github-actions/develop.git" #URL primer repositorio.
          source_branch: "main"
          destination_repo: https://johnduenas1000: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@github.com/jdtest-github-actions/production.git #Repositorio destino.
          destination_branch: "main"