on:
  pull_request:
    types: [closed]
jobs:
  git-sync:
    if: ${{ startsWith(github.event.pull_request.title, 'all') }}
    runs-on: ubuntu-latest
    steps:
      run: echo PR closed => ${{ github.event.pull_request.title }}
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://johnduenas1000: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@github.com/jdtest-github-actions/develop.git" #URL primer repositorio.
          source_branch: "main"
          destination_repo: https://johnduenas1000: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@github.com/jdtest-github-actions/staging.git #Repositorio destino.
          destination_branch: "main"